<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-I93VVF5" failures="1" tests="3" name="Personal Loan" time="0.087" errors="0" timestamp="2024-07-17T10:43:13 IST">
  <testcase classname="packageName.Day1" name="Two" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at packageName.Day1.Two(Day1.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Two -->
  <testcase classname="packageName.Day2" name="loan" time="0.002"/>
  <testcase classname="packageName.Day2" name="ploan" time="0.002"/>
  <testcase classname="packageName.Day1" name="one" time="0.0">
    <ignored/>
  </testcase> <!-- one -->
</testsuite> <!-- Personal Loan -->
